CREATE TABLE enjoycook_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    recipe_id INTEGER
        REFERENCES enjoycook_recipes(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES enjoycook_users(id) ON DELETE CASCADE NOT NULL
);
